/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_System;

import Connector.mySQLConnector;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xanakran
 */
public class Adjust_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Adjust_Menu
     */
    public Adjust_Menu() {
        initComponents();
        try {
        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * FROM Menu";
        ps = mySQLConnector.setConnection().prepareStatement(query);
        rs = ps.executeQuery();
        while (rs.next()) {
            if (rs.getString("itemType").equalsIgnoreCase("Burger")) {
                DefaultTableModel model = (DefaultTableModel) burgerTable.getModel();
                String a = rs.getString("itemID");
                String b = rs.getString("itemName");
                String c = rs.getString("itemPrice");
                model.addRow(new Object[]{a, b, c});
            }
            if (rs.getString("itemType").equalsIgnoreCase("Side")) {
                DefaultTableModel model = (DefaultTableModel) sideTable.getModel();
                String a = rs.getString("itemID");
                String b = rs.getString("itemName");
                String c = rs.getString("itemPrice");
                model.addRow(new Object[]{a, b, c});
            }
            if (rs.getString("itemType").equalsIgnoreCase("Drink")) {
                DefaultTableModel model = (DefaultTableModel) drinkTable.getModel();
                String a = rs.getString("itemID");
                String b = rs.getString("itemName");
                String c = rs.getString("itemPrice");
                model.addRow(new Object[]{a, b, c});
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemsTab = new javax.swing.JTabbedPane();
        burgersTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        burgerTable = new javax.swing.JTable();
        deleteItem = new javax.swing.JLabel();
        itemID = new javax.swing.JLabel();
        newPrice = new javax.swing.JLabel();
        deleteButtonA = new javax.swing.JButton();
        priceText = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        addItem = new javax.swing.JLabel();
        newName = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        sidesTab = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sideTable = new javax.swing.JTable();
        addItem1 = new javax.swing.JLabel();
        newName1 = new javax.swing.JLabel();
        nameText1 = new javax.swing.JTextField();
        newPrice1 = new javax.swing.JLabel();
        priceText1 = new javax.swing.JTextField();
        addButton1 = new javax.swing.JButton();
        itemID1 = new javax.swing.JLabel();
        idText1 = new javax.swing.JTextField();
        deleteButtonA1 = new javax.swing.JButton();
        deleteItem1 = new javax.swing.JLabel();
        drinksTab = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        drinkTable = new javax.swing.JTable();
        deleteItem2 = new javax.swing.JLabel();
        nameText2 = new javax.swing.JTextField();
        newName2 = new javax.swing.JLabel();
        newPrice2 = new javax.swing.JLabel();
        itemID2 = new javax.swing.JLabel();
        idText2 = new javax.swing.JTextField();
        deleteButtonA2 = new javax.swing.JButton();
        priceText2 = new javax.swing.JTextField();
        addButton2 = new javax.swing.JButton();
        addItem2 = new javax.swing.JLabel();
        Homebutton = new javax.swing.JButton();
        Banner = new javax.swing.JLabel();
        BannerColor = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemsTab.setFocusable(false);
        itemsTab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        burgersTab.setBackground(new java.awt.Color(255, 255, 255));
        burgersTab.setOpaque(false);
        burgersTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        burgerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemID", "ItemName", "ItemPrice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        burgerTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(burgerTable);

        burgersTab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 130));

        deleteItem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deleteItem.setText("DELETE ITEM");
        burgersTab.add(deleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 170, 33));

        itemID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        itemID.setText("Enter Item ID:");
        burgersTab.add(itemID, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 180, 33));

        newPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newPrice.setText("New Item Price:");
        burgersTab.add(newPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 210, 33));

        deleteButtonA.setText("Delete Item");
        deleteButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonAActionPerformed(evt);
            }
        });
        burgersTab.add(deleteButtonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 200, 54));
        burgersTab.add(priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 342, 260, 30));
        burgersTab.add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 312, 130, 30));

        addItem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addItem.setText("ADD ITEM");
        burgersTab.add(addItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, 33));

        newName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newName.setText("New Item Name:");
        burgersTab.add(newName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, 33));
        burgersTab.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 282, 260, 30));

        addButton.setText("Add New Item");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        burgersTab.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 470, 54));

        itemsTab.addTab("Burgers", burgersTab);

        sidesTab.setBackground(new java.awt.Color(255, 255, 255));
        sidesTab.setOpaque(false);
        sidesTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemID", "ItemName", "ItemPrice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sideTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(sideTable);

        sidesTab.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 130));

        addItem1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addItem1.setText("ADD ITEM");
        sidesTab.add(addItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, 33));

        newName1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newName1.setText("New Item Name:");
        sidesTab.add(newName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, 33));
        sidesTab.add(nameText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 282, 260, 30));

        newPrice1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newPrice1.setText("New Item Price:");
        sidesTab.add(newPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 210, 33));
        sidesTab.add(priceText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 342, 260, 30));

        addButton1.setText("Add New Item");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });
        sidesTab.add(addButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 470, 54));

        itemID1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        itemID1.setText("Enter Item ID:");
        sidesTab.add(itemID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 180, 33));
        sidesTab.add(idText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 312, 130, 30));

        deleteButtonA1.setText("Delete Item");
        deleteButtonA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonA1ActionPerformed(evt);
            }
        });
        sidesTab.add(deleteButtonA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 200, 54));

        deleteItem1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deleteItem1.setText("DELETE ITEM");
        sidesTab.add(deleteItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 170, 33));

        itemsTab.addTab("Sides", sidesTab);

        drinksTab.setBackground(new java.awt.Color(255, 255, 255));
        drinksTab.setOpaque(false);
        drinksTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drinkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemID", "ItemName", "ItemPrice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drinkTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(drinkTable);

        drinksTab.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 130));

        deleteItem2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deleteItem2.setText("DELETE ITEM");
        drinksTab.add(deleteItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 170, 33));
        drinksTab.add(nameText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 282, 260, 30));

        newName2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newName2.setText("New Item Name:");
        drinksTab.add(newName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, 33));

        newPrice2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newPrice2.setText("New Item Price:");
        drinksTab.add(newPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 210, 33));

        itemID2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        itemID2.setText("Enter Item ID:");
        drinksTab.add(itemID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 180, 33));
        drinksTab.add(idText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 312, 130, 30));

        deleteButtonA2.setText("Delete Item");
        deleteButtonA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonA2ActionPerformed(evt);
            }
        });
        drinksTab.add(deleteButtonA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 200, 54));
        drinksTab.add(priceText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 342, 260, 30));

        addButton2.setText("Add New Item");
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });
        drinksTab.add(addButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 470, 54));

        addItem2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addItem2.setText("ADD ITEM");
        drinksTab.add(addItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, 33));

        itemsTab.addTab("Drinks", drinksTab);

        getContentPane().add(itemsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 990, 500));

        Homebutton.setText("Main Menu");
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 129, 54));

        Banner.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        Banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Banner.png"))); // NOI18N
        Banner.setText("Johnny's Burgers");
        getContentPane().add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 480, -1));

        BannerColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Color.png"))); // NOI18N
        BannerColor.setText("jLabel1");
        BannerColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(BannerColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Menu_Picture.png"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed

    }//GEN-LAST:event_HomebuttonActionPerformed

    private void deleteButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonAActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton1ActionPerformed

    private void deleteButtonA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonA1ActionPerformed

    private void deleteButtonA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonA2ActionPerformed

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adjust_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adjust_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adjust_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adjust_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adjust_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Banner;
    private javax.swing.JLabel BannerColor;
    private javax.swing.JButton Homebutton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addButton2;
    private javax.swing.JLabel addItem;
    private javax.swing.JLabel addItem1;
    private javax.swing.JLabel addItem2;
    private javax.swing.JTable burgerTable;
    private javax.swing.JPanel burgersTab;
    private javax.swing.JButton deleteButtonA;
    private javax.swing.JButton deleteButtonA1;
    private javax.swing.JButton deleteButtonA2;
    private javax.swing.JLabel deleteItem;
    private javax.swing.JLabel deleteItem1;
    private javax.swing.JLabel deleteItem2;
    private javax.swing.JTable drinkTable;
    private javax.swing.JPanel drinksTab;
    private javax.swing.JTextField idText;
    private javax.swing.JTextField idText1;
    private javax.swing.JTextField idText2;
    private javax.swing.JLabel itemID;
    private javax.swing.JLabel itemID1;
    private javax.swing.JLabel itemID2;
    private javax.swing.JTabbedPane itemsTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nameText1;
    private javax.swing.JTextField nameText2;
    private javax.swing.JLabel newName;
    private javax.swing.JLabel newName1;
    private javax.swing.JLabel newName2;
    private javax.swing.JLabel newPrice;
    private javax.swing.JLabel newPrice1;
    private javax.swing.JLabel newPrice2;
    private javax.swing.JTextField priceText;
    private javax.swing.JTextField priceText1;
    private javax.swing.JTextField priceText2;
    private javax.swing.JTable sideTable;
    private javax.swing.JPanel sidesTab;
    // End of variables declaration//GEN-END:variables
}
