/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_System;

/**
 *
 * @author Xanakran
 */
public class History extends javax.swing.JFrame {

    /**
     * Creates new form History
     */
    public History() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public History(String ID, String info, String status) {
        initComponents();
        this.setLocationRelativeTo(null);
        idText.setText(ID);
        orderInfo.setText(info);
        orderStatusText.setText(status);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderStatusLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        historyLabel = new javax.swing.JLabel();
        orderInfo = new javax.swing.JTextArea();
        orderStatusText = new javax.swing.JTextArea();
        orderInfoLabel = new javax.swing.JLabel();
        BannerColor = new javax.swing.JLabel();
        orderIDLabel1 = new javax.swing.JLabel();
        idText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderStatusLabel.setBackground(new java.awt.Color(0, 0, 0));
        orderStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        orderStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderStatusLabel.setText("Order Status");
        orderStatusLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        orderStatusLabel.setOpaque(true);
        getContentPane().add(orderStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 130, 20));

        closeButton.setText("Close Window");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 129, 54));

        historyLabel.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        historyLabel.setText("ORDER HISTORY");
        getContentPane().add(historyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 42));

        orderInfo.setEditable(false);
        orderInfo.setColumns(20);
        orderInfo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        orderInfo.setRows(5);
        orderInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(orderInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 670, 420));

        orderStatusText.setEditable(false);
        orderStatusText.setColumns(20);
        orderStatusText.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        orderStatusText.setRows(5);
        orderStatusText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        orderStatusText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(orderStatusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 130, 420));

        orderInfoLabel.setBackground(new java.awt.Color(0, 0, 0));
        orderInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        orderInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderInfoLabel.setText("Order Info");
        orderInfoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        orderInfoLabel.setOpaque(true);
        getContentPane().add(orderInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 670, 20));

        BannerColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Color.png"))); // NOI18N
        BannerColor.setText("jLabel1");
        BannerColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(BannerColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 70));

        orderIDLabel1.setBackground(new java.awt.Color(0, 0, 0));
        orderIDLabel1.setForeground(new java.awt.Color(255, 255, 255));
        orderIDLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderIDLabel1.setText("OrderID");
        orderIDLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        orderIDLabel1.setOpaque(true);
        getContentPane().add(orderIDLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 20));

        idText.setEditable(false);
        idText.setColumns(20);
        idText.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        idText.setRows(5);
        idText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        idText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BannerColor;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel historyLabel;
    private javax.swing.JTextArea idText;
    private javax.swing.JLabel orderIDLabel1;
    private javax.swing.JTextArea orderInfo;
    private javax.swing.JLabel orderInfoLabel;
    private javax.swing.JLabel orderStatusLabel;
    private javax.swing.JTextArea orderStatusText;
    // End of variables declaration//GEN-END:variables
}
