package Restaurant_System;

import java.sql.Connection;
import Connector.mySQLConnector;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Xanakran
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        returnButton = new javax.swing.JButton();
        Customer_btn = new javax.swing.JRadioButton();
        Manager_btn = new javax.swing.JRadioButton();
        Username_text = new javax.swing.JTextField();
        Enter_Username = new javax.swing.JLabel();
        Enter_Password = new javax.swing.JLabel();
        Password_text = new javax.swing.JPasswordField();
        Login_Text = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        BannerColor = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 3, -1, -1));

        buttonGroup1.add(Customer_btn);
        Customer_btn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Customer_btn.setForeground(new java.awt.Color(255, 255, 255));
        Customer_btn.setText("I'm a Customer");
        Customer_btn.setOpaque(false);
        Customer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Customer_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, -1));

        buttonGroup1.add(Manager_btn);
        Manager_btn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Manager_btn.setForeground(new java.awt.Color(255, 255, 255));
        Manager_btn.setText("I'm a Manager");
        Manager_btn.setOpaque(false);
        Manager_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Manager_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, -1));

        Username_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_textActionPerformed(evt);
            }
        });
        getContentPane().add(Username_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 119, -1));

        Enter_Username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Enter_Username.setForeground(new java.awt.Color(255, 255, 255));
        Enter_Username.setText("Enter Username: ");
        getContentPane().add(Enter_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 118, 20));

        Enter_Password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Enter_Password.setForeground(new java.awt.Color(255, 255, 255));
        Enter_Password.setText("Enter Password: ");
        getContentPane().add(Enter_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 118, 20));
        getContentPane().add(Password_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 120, -1));

        Login_Text.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        Login_Text.setText("LOGIN");
        getContentPane().add(Login_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 42));

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 178, 64));

        BannerColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Color.png"))); // NOI18N
        BannerColor.setText("jLabel1");
        BannerColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(BannerColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.png"))); // NOI18N
        Background.setText("jLabel4");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_textActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
    try
                {
                    String username = Username_text.getText();
                    String password = String.valueOf(Password_text.getPassword());
                    ResultSet rs;
                    PreparedStatement ps;
                    
                    if (!username.isEmpty() && !password.isEmpty())
                    {
                        if (Manager_btn.isSelected())
                        {
                            //logging in as manager
                            String query = "SELECT * FROM Manager WHERE managerUsername = ? AND managerPassword = ?";
                            ps = mySQLConnector.setConnection().prepareStatement(query);
                            ps.setString(1, username);
                            ps.setString(2, password);
                            rs = ps.executeQuery();
                            //rs = s.executeQuery(query);
                            
                            //manager login successful
                            if (rs.next())
                            {
                                String mname = rs.getString("managerName");
                                Manager_Menu mm = new Manager_Menu(username, mname);
                                mm.setVisible(true);
                                this.dispose();
                            }
                            //manager login failed
                            else {
                                JOptionPane.showMessageDialog(null, "Username or Password incorrect, try again.", "LOGIN FAILED", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                        else if (Customer_btn.isSelected())
                        {
                            //logging in as customer
                            String query = "SELECT * FROM Customer WHERE customerUsername = ? AND customerPassword = ? ";
                            ps = mySQLConnector.setConnection().prepareStatement(query);
                            ps.setString(1, username);
                            ps.setString(2, password);
                            rs = ps.executeQuery();
                            //customer login successful
                            if (rs.next())
                            {
                                String cname = rs.getString("customerName");
                                String address = rs.getString("customerAddress");
                                int zipcode = rs.getInt("customerZipcode");
                                int rewards = rs.getInt("customerRewards");
                                Customer_Menu cm = new Customer_Menu(username, cname, address, zipcode, rewards);
                                cm.setVisible(true);
                                this.dispose();
                            }
                            
                            //customer login failed
                            else {
                                JOptionPane.showMessageDialog(null, "Username or Password incorrect, try again.", "LOGIN FAILED", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Please select whether you are a Manager or Customer.", "LOGIN ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                            
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Please fill both TextFields", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e)
                {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }           
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void Manager_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_btnActionPerformed

    private void Customer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_btnActionPerformed

    }//GEN-LAST:event_Customer_btnActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        Restaurant_System rs = new Restaurant_System();
        rs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BannerColor;
    private javax.swing.JRadioButton Customer_btn;
    private javax.swing.JLabel Enter_Password;
    private javax.swing.JLabel Enter_Username;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Login_Text;
    private javax.swing.JRadioButton Manager_btn;
    private javax.swing.JPasswordField Password_text;
    private javax.swing.JTextField Username_text;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
