package Restaurant_System;
// mySQLConnector;

import connector.mySQLConnector;
import java.sql.ResultSet;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Xanakran
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username_text = new javax.swing.JTextField();
        Enter_Username = new javax.swing.JLabel();
        Enter_Password = new javax.swing.JLabel();
        Password_Text = new javax.swing.JTextField();
        Login_Text = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        BannerColor = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_textActionPerformed(evt);
            }
        });
        getContentPane().add(Username_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 119, -1));

        Enter_Username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Enter_Username.setForeground(new java.awt.Color(255, 255, 255));
        Enter_Username.setText("Enter Username: ");
        getContentPane().add(Enter_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 118, -1));

        Enter_Password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Enter_Password.setForeground(new java.awt.Color(255, 255, 255));
        Enter_Password.setText("Enter Password: ");
        getContentPane().add(Enter_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 118, -1));

        Password_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TextActionPerformed(evt);
            }
        });
        getContentPane().add(Password_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 119, -1));

        Login_Text.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        Login_Text.setText("LOGIN");
        getContentPane().add(Login_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 42));

        LoginButton.setText("jButton1");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 178, 64));

        BannerColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Color.png"))); // NOI18N
        BannerColor.setText("jLabel1");
        BannerColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(BannerColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.png"))); // NOI18N
        Background.setText("jLabel4");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_textActionPerformed

    private void Password_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TextActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String id = Username_text.getText();
        ResultSet rs = null;
        rs = mySQLConnector.search("select * from sonoo.users where id = " + id + ";");
        if (rs != null)
            System.out.println("Login Successful you exist in the db!");
        else
            System.out.println("Login unsuccessful, please try a different username password combination");
        
// TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BannerColor;
    private javax.swing.JLabel Enter_Password;
    private javax.swing.JLabel Enter_Username;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Login_Text;
    private javax.swing.JTextField Password_Text;
    private javax.swing.JTextField Username_text;
    // End of variables declaration//GEN-END:variables
}
