/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_System;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Xanakran
 */
public class Menu extends javax.swing.JFrame {

    private String currCart = "";
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        itemsTab = new javax.swing.JTabbedPane();
        burgersTab = new javax.swing.JPanel();
        Burger4 = new javax.swing.JLabel();
        Burger1 = new javax.swing.JLabel();
        Burger2 = new javax.swing.JLabel();
        Burger3 = new javax.swing.JLabel();
        checkoutBurgerMenuBtn = new javax.swing.JButton();
        addBaconCheeseBurgerbtn = new javax.swing.JButton();
        addCheesebgrBtn = new javax.swing.JButton();
        addBaconBgrBtn = new javax.swing.JButton();
        addHambgrBtn = new javax.swing.JButton();
        addDblPattyBgrBtn = new javax.swing.JButton();
        burgersText = new javax.swing.JTextArea();
        txtShadow1 = new javax.swing.JLabel();
        sidesTab = new javax.swing.JPanel();
        Sides1 = new javax.swing.JLabel();
        Sides2 = new javax.swing.JLabel();
        Sides3 = new javax.swing.JLabel();
        Sides4 = new javax.swing.JLabel();
        addSmallFryBtn = new javax.swing.JButton();
        addMediumFryBtn = new javax.swing.JButton();
        addLargeFryBtn = new javax.swing.JButton();
        addOnionRingsBtn = new javax.swing.JButton();
        addCurlyFryBtn = new javax.swing.JButton();
        checkoutSidesMenuBtn = new javax.swing.JButton();
        sidesText = new javax.swing.JTextArea();
        txtShadow2 = new javax.swing.JLabel();
        drinksTab = new javax.swing.JPanel();
        checkoutBtn = new javax.swing.JButton();
        Drink3 = new javax.swing.JLabel();
        Drink1 = new javax.swing.JLabel();
        Drink4 = new javax.swing.JLabel();
        Drink2 = new javax.swing.JLabel();
        addBottleWaterBtn = new javax.swing.JButton();
        addSmallSoftDrinkBtn = new javax.swing.JButton();
        addMediumSoftDrinkBtn = new javax.swing.JButton();
        addLargeSoftDrinkBtn = new javax.swing.JButton();
        addLemonadeBtn = new javax.swing.JButton();
        checkoutDrinkMenuBtn = new javax.swing.JButton();
        drinksText = new javax.swing.JTextArea();
        txtShadow3 = new javax.swing.JLabel();
        Homebutton = new javax.swing.JButton();
        Banner = new javax.swing.JLabel();
        BannerColor = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        jButton12.setText("jButton12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemsTab.setFocusable(false);
        itemsTab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        burgersTab.setBackground(new java.awt.Color(255, 255, 255));
        burgersTab.setOpaque(false);
        burgersTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Burger4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Burger4.png"))); // NOI18N
        Burger4.setText("Burger1");
        burgersTab.add(Burger4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 210, 130));

        Burger1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Burger1.png"))); // NOI18N
        Burger1.setText("Burger1");
        Burger1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        burgersTab.add(Burger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 200, 130));

        Burger2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Burger2.png"))); // NOI18N
        Burger2.setText("Burger1");
        Burger2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        burgersTab.add(Burger2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 210, 130));

        Burger3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Burger3.png"))); // NOI18N
        Burger3.setText("Burger1");
        burgersTab.add(Burger3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 210, 130));

        checkoutBurgerMenuBtn.setBackground(java.awt.Color.red);
        checkoutBurgerMenuBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        checkoutBurgerMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBurgerMenuBtn.setText("Checkout");
        checkoutBurgerMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBurgerMenuBtnActionPerformed(evt);
            }
        });
        burgersTab.add(checkoutBurgerMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        addBaconCheeseBurgerbtn.setBackground(new java.awt.Color(21, 180, 47));
        addBaconCheeseBurgerbtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addBaconCheeseBurgerbtn.setText("Add to cart");
        addBaconCheeseBurgerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBaconCheeseBurgerbtnActionPerformed(evt);
            }
        });
        burgersTab.add(addBaconCheeseBurgerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        addCheesebgrBtn.setBackground(new java.awt.Color(21, 180, 47));
        addCheesebgrBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addCheesebgrBtn.setText("Add to cart");
        addCheesebgrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCheesebgrBtnActionPerformed(evt);
            }
        });
        burgersTab.add(addCheesebgrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        addBaconBgrBtn.setBackground(new java.awt.Color(21, 180, 47));
        addBaconBgrBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addBaconBgrBtn.setText("Add to cart");
        addBaconBgrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBaconBgrBtnActionPerformed(evt);
            }
        });
        burgersTab.add(addBaconBgrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        addHambgrBtn.setBackground(new java.awt.Color(21, 180, 47));
        addHambgrBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addHambgrBtn.setText("Add to cart");
        addHambgrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHambgrBtnActionPerformed(evt);
            }
        });
        burgersTab.add(addHambgrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        addDblPattyBgrBtn.setBackground(new java.awt.Color(21, 180, 47));
        addDblPattyBgrBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addDblPattyBgrBtn.setText("Add to cart");
        addDblPattyBgrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDblPattyBgrBtnActionPerformed(evt);
            }
        });
        burgersTab.add(addDblPattyBgrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        burgersText.setEditable(false);
        burgersText.setBackground(new java.awt.Color(0,0,0,0));
        burgersText.setColumns(20);
        burgersText.setFont(new java.awt.Font("Rockwell", 3, 30)); // NOI18N
        burgersText.setForeground(new java.awt.Color(255, 255, 255));
        burgersText.setRows(5);
        burgersText.setText("Hamburger : $4.99\nCheeseburger : $5.99\nBaconburger : $5.99\nBacon Cheeseburger : $6.99\nDouble Patty Burger : $5.99");
        burgersText.setBorder(null);
        burgersTab.add(burgersText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 560, 400));

        txtShadow1.setBackground(new java.awt.Color(0,0,0,128));
        txtShadow1.setOpaque(true);
        burgersTab.add(txtShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 460));

        itemsTab.addTab("Burgers", burgersTab);

        sidesTab.setBackground(new java.awt.Color(255, 255, 255));
        sidesTab.setOpaque(false);
        sidesTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sides1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Sides1.png"))); // NOI18N
        Sides1.setText("Burger1");
        Sides1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        sidesTab.add(Sides1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 210, 130));

        Sides2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Sides4.png"))); // NOI18N
        Sides2.setText("Burger1");
        Sides2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        sidesTab.add(Sides2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 220, 130));

        Sides3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Sides2.png"))); // NOI18N
        Sides3.setText("Burger1");
        Sides3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        sidesTab.add(Sides3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 210, 130));

        Sides4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Sides3.png"))); // NOI18N
        Sides4.setText("Burger1");
        Sides4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        sidesTab.add(Sides4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 220, 130));

        addSmallFryBtn.setBackground(new java.awt.Color(21, 180, 47));
        addSmallFryBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addSmallFryBtn.setText("Add to cart");
        addSmallFryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSmallFryBtnActionPerformed(evt);
            }
        });
        sidesTab.add(addSmallFryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        addMediumFryBtn.setBackground(new java.awt.Color(21, 180, 47));
        addMediumFryBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addMediumFryBtn.setText("Add to cart");
        addMediumFryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMediumFryBtnActionPerformed(evt);
            }
        });
        sidesTab.add(addMediumFryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        addLargeFryBtn.setBackground(new java.awt.Color(21, 180, 47));
        addLargeFryBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addLargeFryBtn.setText("Add to cart");
        addLargeFryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLargeFryBtnActionPerformed(evt);
            }
        });
        sidesTab.add(addLargeFryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        addOnionRingsBtn.setBackground(new java.awt.Color(21, 180, 47));
        addOnionRingsBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addOnionRingsBtn.setText("Add to cart");
        addOnionRingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOnionRingsBtnActionPerformed(evt);
            }
        });
        sidesTab.add(addOnionRingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        addCurlyFryBtn.setBackground(new java.awt.Color(21, 180, 47));
        addCurlyFryBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addCurlyFryBtn.setText("Add to cart");
        addCurlyFryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCurlyFryBtnActionPerformed(evt);
            }
        });
        sidesTab.add(addCurlyFryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        checkoutSidesMenuBtn.setBackground(java.awt.Color.red);
        checkoutSidesMenuBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        checkoutSidesMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutSidesMenuBtn.setText("Checkout");
        checkoutSidesMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutSidesMenuBtnActionPerformed(evt);
            }
        });
        sidesTab.add(checkoutSidesMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        sidesText.setEditable(false);
        sidesText.setBackground(new java.awt.Color(0,0,0,0));
        sidesText.setColumns(20);
        sidesText.setFont(new java.awt.Font("Rockwell", 3, 30)); // NOI18N
        sidesText.setForeground(new java.awt.Color(255, 255, 255));
        sidesText.setRows(5);
        sidesText.setText("Small Fries : $1.99\nMedium Fries : $2.49\nLarge Fries : $2.99\nOnion Rings : $2.99\nCurly Fries : $2.99\n");
        sidesText.setBorder(null);
        sidesTab.add(sidesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 560, 400));

        txtShadow2.setBackground(new java.awt.Color(0,0,0,128));
        txtShadow2.setOpaque(true);
        sidesTab.add(txtShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 460));

        itemsTab.addTab("Sides", sidesTab);

        drinksTab.setBackground(new java.awt.Color(255, 255, 255));
        drinksTab.setOpaque(false);
        drinksTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkoutBtn.setBackground(new java.awt.Color(255, 0, 51));
        checkoutBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBtn.setText("Checkout");
        drinksTab.add(checkoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        Drink3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Drinks3.png"))); // NOI18N
        Drink3.setText("Burger1");
        Drink3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        drinksTab.add(Drink3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 220, 150));

        Drink1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Drinks1.png"))); // NOI18N
        Drink1.setText("Burger1");
        Drink1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        drinksTab.add(Drink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 220, 150));

        Drink4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Drinks4.png"))); // NOI18N
        Drink4.setText("Burger1");
        Drink4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        drinksTab.add(Drink4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 230, 150));

        Drink2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Drinks2.png"))); // NOI18N
        Drink2.setText("Burger1");
        Drink2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        drinksTab.add(Drink2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 220, 150));

        addBottleWaterBtn.setBackground(new java.awt.Color(21, 180, 47));
        addBottleWaterBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addBottleWaterBtn.setText("Add to cart");
        addBottleWaterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBottleWaterBtnActionPerformed(evt);
            }
        });
        drinksTab.add(addBottleWaterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        addSmallSoftDrinkBtn.setBackground(new java.awt.Color(21, 180, 47));
        addSmallSoftDrinkBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addSmallSoftDrinkBtn.setText("Add to cart");
        addSmallSoftDrinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSmallSoftDrinkBtnActionPerformed(evt);
            }
        });
        drinksTab.add(addSmallSoftDrinkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        addMediumSoftDrinkBtn.setBackground(new java.awt.Color(21, 180, 47));
        addMediumSoftDrinkBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addMediumSoftDrinkBtn.setText("Add to cart");
        addMediumSoftDrinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMediumSoftDrinkBtnActionPerformed(evt);
            }
        });
        drinksTab.add(addMediumSoftDrinkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        addLargeSoftDrinkBtn.setBackground(new java.awt.Color(21, 180, 47));
        addLargeSoftDrinkBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addLargeSoftDrinkBtn.setText("Add to cart");
        addLargeSoftDrinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLargeSoftDrinkBtnActionPerformed(evt);
            }
        });
        drinksTab.add(addLargeSoftDrinkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        addLemonadeBtn.setBackground(new java.awt.Color(21, 180, 47));
        addLemonadeBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addLemonadeBtn.setText("Add to cart");
        addLemonadeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLemonadeBtnActionPerformed(evt);
            }
        });
        drinksTab.add(addLemonadeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        checkoutDrinkMenuBtn.setBackground(java.awt.Color.red);
        checkoutDrinkMenuBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        checkoutDrinkMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutDrinkMenuBtn.setText("Checkout");
        checkoutDrinkMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutDrinkMenuBtnActionPerformed(evt);
            }
        });
        drinksTab.add(checkoutDrinkMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        drinksText.setEditable(false);
        drinksText.setBackground(new java.awt.Color(0,0,0,0));
        drinksText.setColumns(20);
        drinksText.setFont(new java.awt.Font("Rockwell", 3, 30)); // NOI18N
        drinksText.setForeground(new java.awt.Color(255, 255, 255));
        drinksText.setRows(5);
        drinksText.setText("Bottled Water : $0.99\nSmall Softdrink : $1.49\nMedium Softdrink : $1.99\nLarge Softdrink : $2.29\nLemonade : $1.99\n");
        drinksText.setBorder(null);
        drinksTab.add(drinksText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 560, 400));

        txtShadow3.setBackground(new java.awt.Color(0,0,0,128));
        txtShadow3.setOpaque(true);
        drinksTab.add(txtShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 460));

        itemsTab.addTab("Drinks", drinksTab);

        getContentPane().add(itemsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 990, 500));

        Homebutton.setText("Main Menu");
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 129, 54));

        Banner.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        Banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Banner.png"))); // NOI18N
        Banner.setText("Johnny's Burgers");
        getContentPane().add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 480, -1));

        BannerColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Color.png"))); // NOI18N
        BannerColor.setText("jLabel1");
        BannerColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(BannerColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Menu_Picture.png"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        jButton14.setText("jButton14");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
        Restaurant_System rs = new Restaurant_System();
        rs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomebuttonActionPerformed


//              adding burgers by combobox
    private void checkoutBurgerMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBurgerMenuBtnActionPerformed
        // TODO add your handling code here:
                        
    }//GEN-LAST:event_checkoutBurgerMenuBtnActionPerformed

//              adding burgers by button
    private void addBaconCheeseBurgerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBaconCheeseBurgerbtnActionPerformed
        this.currCart.concat(1 + " baconCheeseBurger ");
    }//GEN-LAST:event_addBaconCheeseBurgerbtnActionPerformed
    private void addCheesebgrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCheesebgrBtnActionPerformed
        this.currCart.concat(1 + " cheeseBurger ");
    }//GEN-LAST:event_addCheesebgrBtnActionPerformed

    private void addBaconBgrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBaconBgrBtnActionPerformed
        this.currCart.concat(1 + " baconBurger ");
    }//GEN-LAST:event_addBaconBgrBtnActionPerformed

    private void addHambgrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHambgrBtnActionPerformed
        this.currCart.concat(1 + " hamBurger ");
    }//GEN-LAST:event_addHambgrBtnActionPerformed

    private void addDblPattyBgrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDblPattyBgrBtnActionPerformed
        this.currCart.concat(1 + " doublePattyBurger ");
    }//GEN-LAST:event_addDblPattyBgrBtnActionPerformed

    private void addSmallFryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSmallFryBtnActionPerformed
        this.currCart.concat(1 + " smallFry ");
    }//GEN-LAST:event_addSmallFryBtnActionPerformed

    private void addMediumFryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMediumFryBtnActionPerformed
        this.currCart.concat(1 + " mediumFry ");
    }//GEN-LAST:event_addMediumFryBtnActionPerformed

    private void addLargeFryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLargeFryBtnActionPerformed
        this.currCart.concat(1 + " largeFry ");
    }//GEN-LAST:event_addLargeFryBtnActionPerformed

    private void addOnionRingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOnionRingsBtnActionPerformed
        this.currCart.concat(1 + " onionRings ");
    }//GEN-LAST:event_addOnionRingsBtnActionPerformed

    private void addCurlyFryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCurlyFryBtnActionPerformed
        this.currCart.concat(1 + " curlyFry ");
    }//GEN-LAST:event_addCurlyFryBtnActionPerformed

    private void checkoutSidesMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutSidesMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutSidesMenuBtnActionPerformed

    private void addBottleWaterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBottleWaterBtnActionPerformed
        this.currCart.concat(1 + " bottleWater ");
    }//GEN-LAST:event_addBottleWaterBtnActionPerformed

    private void addSmallSoftDrinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSmallSoftDrinkBtnActionPerformed
        this.currCart.concat(1 + " smallSoftDrink ");
    }//GEN-LAST:event_addSmallSoftDrinkBtnActionPerformed

    private void addMediumSoftDrinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMediumSoftDrinkBtnActionPerformed
        this.currCart.concat(1 + " mediumSoftdrink ");
    }//GEN-LAST:event_addMediumSoftDrinkBtnActionPerformed

    private void addLargeSoftDrinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLargeSoftDrinkBtnActionPerformed
        this.currCart.concat(1 + " largeSoftDrink ");
    }//GEN-LAST:event_addLargeSoftDrinkBtnActionPerformed

    private void addLemonadeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLemonadeBtnActionPerformed
        this.currCart.concat(1 + " lemonade ");
    }//GEN-LAST:event_addLemonadeBtnActionPerformed

    private void checkoutDrinkMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutDrinkMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutDrinkMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Banner;
    private javax.swing.JLabel BannerColor;
    private javax.swing.JLabel Burger1;
    private javax.swing.JLabel Burger2;
    private javax.swing.JLabel Burger3;
    private javax.swing.JLabel Burger4;
    private javax.swing.JLabel Drink1;
    private javax.swing.JLabel Drink2;
    private javax.swing.JLabel Drink3;
    private javax.swing.JLabel Drink4;
    private javax.swing.JButton Homebutton;
    private javax.swing.JLabel Sides1;
    private javax.swing.JLabel Sides2;
    private javax.swing.JLabel Sides3;
    private javax.swing.JLabel Sides4;
    private javax.swing.JButton addBaconBgrBtn;
    private javax.swing.JButton addBaconCheeseBurgerbtn;
    private javax.swing.JButton addBottleWaterBtn;
    private javax.swing.JButton addCheesebgrBtn;
    private javax.swing.JButton addCurlyFryBtn;
    private javax.swing.JButton addDblPattyBgrBtn;
    private javax.swing.JButton addHambgrBtn;
    private javax.swing.JButton addLargeFryBtn;
    private javax.swing.JButton addLargeSoftDrinkBtn;
    private javax.swing.JButton addLemonadeBtn;
    private javax.swing.JButton addMediumFryBtn;
    private javax.swing.JButton addMediumSoftDrinkBtn;
    private javax.swing.JButton addOnionRingsBtn;
    private javax.swing.JButton addSmallFryBtn;
    private javax.swing.JButton addSmallSoftDrinkBtn;
    private javax.swing.JPanel burgersTab;
    private javax.swing.JTextArea burgersText;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JButton checkoutBurgerMenuBtn;
    private javax.swing.JButton checkoutDrinkMenuBtn;
    private javax.swing.JButton checkoutSidesMenuBtn;
    private javax.swing.JPanel drinksTab;
    private javax.swing.JTextArea drinksText;
    private javax.swing.JTabbedPane itemsTab;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel sidesTab;
    private javax.swing.JTextArea sidesText;
    private javax.swing.JLabel txtShadow1;
    private javax.swing.JLabel txtShadow2;
    private javax.swing.JLabel txtShadow3;
    // End of variables declaration//GEN-END:variables
}
