/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_System;

/**
 *
 * @author Xanakran
 */
public class Sign_Up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Up
     */
    public Sign_Up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register_Label = new javax.swing.JLabel();
        R_Username = new javax.swing.JLabel();
        R_Password = new javax.swing.JLabel();
        R_Username_Text = new javax.swing.JTextField();
        R_Password_Text = new javax.swing.JTextField();
        Register_Button = new javax.swing.JButton();
        R_Name = new javax.swing.JLabel();
        R_Email = new javax.swing.JLabel();
        R_Mobile = new javax.swing.JLabel();
        R_Name_Text = new javax.swing.JTextField();
        R_Email_Text = new javax.swing.JTextField();
        R_Mobile_Text = new javax.swing.JTextField();
        R_Address = new javax.swing.JLabel();
        R_Addressl_Text = new javax.swing.JTextField();
        BannerColor = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register_Label.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        Register_Label.setText("REGISTER ACCOUNT");
        getContentPane().add(Register_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 42));

        R_Username.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        R_Username.setForeground(new java.awt.Color(255, 255, 255));
        R_Username.setText("Enter Username: ");
        getContentPane().add(R_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 100, 118, -1));

        R_Password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        R_Password.setForeground(new java.awt.Color(255, 255, 255));
        R_Password.setText("Enter Password: ");
        getContentPane().add(R_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 138, 118, -1));

        R_Username_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Username_TextActionPerformed(evt);
            }
        });
        getContentPane().add(R_Username_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 97, 201, -1));

        R_Password_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Password_TextActionPerformed(evt);
            }
        });
        getContentPane().add(R_Password_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 135, 201, -1));

        Register_Button.setText("Register");
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Register_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 347, 390, 93));

        R_Name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        R_Name.setForeground(new java.awt.Color(255, 255, 255));
        R_Name.setText("Enter Name: ");
        getContentPane().add(R_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 176, 118, -1));

        R_Email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        R_Email.setForeground(new java.awt.Color(255, 255, 255));
        R_Email.setText("Enter Email Address: ");
        getContentPane().add(R_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 215, -1, -1));

        R_Mobile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        R_Mobile.setForeground(new java.awt.Color(255, 255, 255));
        R_Mobile.setText("Enter Mobile Phone #: ");
        getContentPane().add(R_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 256, -1, -1));

        R_Name_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Name_TextActionPerformed(evt);
            }
        });
        getContentPane().add(R_Name_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 173, 201, -1));

        R_Email_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Email_TextActionPerformed(evt);
            }
        });
        getContentPane().add(R_Email_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 212, 201, -1));

        R_Mobile_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Mobile_TextActionPerformed(evt);
            }
        });
        getContentPane().add(R_Mobile_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 253, 201, -1));

        R_Address.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        R_Address.setForeground(new java.awt.Color(255, 255, 255));
        R_Address.setText("Enter Address: ");
        getContentPane().add(R_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 294, -1, -1));

        R_Addressl_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Addressl_TextActionPerformed(evt);
            }
        });
        getContentPane().add(R_Addressl_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 291, 201, -1));

        BannerColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Color.png"))); // NOI18N
        BannerColor.setText("jLabel1");
        BannerColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(BannerColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.png"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R_Username_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Username_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Username_TextActionPerformed

    private void R_Password_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Password_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Password_TextActionPerformed

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Register_ButtonActionPerformed

    private void R_Name_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Name_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Name_TextActionPerformed

    private void R_Email_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Email_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Email_TextActionPerformed

    private void R_Mobile_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Mobile_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Mobile_TextActionPerformed

    private void R_Addressl_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Addressl_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Addressl_TextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BannerColor;
    private javax.swing.JLabel R_Address;
    private javax.swing.JTextField R_Addressl_Text;
    private javax.swing.JLabel R_Email;
    private javax.swing.JTextField R_Email_Text;
    private javax.swing.JLabel R_Mobile;
    private javax.swing.JTextField R_Mobile_Text;
    private javax.swing.JLabel R_Name;
    private javax.swing.JTextField R_Name_Text;
    private javax.swing.JLabel R_Password;
    private javax.swing.JTextField R_Password_Text;
    private javax.swing.JLabel R_Username;
    private javax.swing.JTextField R_Username_Text;
    private javax.swing.JButton Register_Button;
    private javax.swing.JLabel Register_Label;
    // End of variables declaration//GEN-END:variables
}
